// packages/heroui/src/components/auth/two-factor/enable-two-factor-dialog.tsx
import { createQrCodeSvgData, validateStringLength } from "@better-auth-ui/core"
import type {
  TwoFactorAuthClient,
  TwoFactorMethod
} from "@better-auth-ui/core/plugins/two-factor"
import {
  useAuth,
  useAuthPlugin,
  useCopyToClipboard
} from "@better-auth-ui/react"
import {
  useEnableTwoFactor,
  useVerifyTotp
} from "@better-auth-ui/react/plugins/two-factor"
import {
  Check,
  Copy,
  Envelope,
  ShieldCheck,
  Smartphone
} from "@gravity-ui/icons"
import {
  AlertDialog,
  Button,
  Input,
  InputGroup,
  Label,
  Tabs,
  TextField,
  toast
} from "@heroui/react"
import { useMemo, useState } from "react"

import { twoFactorPlugin } from "../../../lib/auth/two-factor-plugin"
import { useTwoFactorPasswordRequirement } from "../../../lib/auth/use-two-factor-password"
import {
  isAuthFormFieldInvalid,
  submitAuthForm,
  useAuthForm
} from "../auth-form"
import { OtpField } from "../otp-field"
import { BackupCodes } from "./backup-codes"

type EnrollmentStep = "password" | "verify" | "backupCodes"

export type EnableTwoFactorDialogProps = {
  isOpen: boolean
  onOpenChange: (open: boolean) => void
}

/**
 * Two-factor enrollment with authenticator-app and delivered-code methods.
 *
 * TOTP continues through QR verification and backup-code capture. OTP becomes
 * active as soon as Better Auth accepts the enrollment request.
 *
 * @param isOpen - Whether the dialog is open.
 * @param onOpenChange - Called when the dialog requests an open state change.
 */
export function EnableTwoFactorDialog({
  isOpen,
  onOpenChange
}: EnableTwoFactorDialogProps) {
  const { authClient, localization } = useAuth()
  const {
    codeLength,
    enrollmentMethods,
    localization: twoFactorLocalization
  } = useAuthPlugin(twoFactorPlugin)
  const { isPending: isResolvingPasswordRequirement, requiresPassword } =
    useTwoFactorPasswordRequirement()

  const twoFactorClient = authClient as TwoFactorAuthClient

  const [step, setStep] = useState<EnrollmentStep>("password")
  const [method, setMethod] = useState<TwoFactorMethod>(
    enrollmentMethods[0] ?? "totp"
  )
  const [totpUri, setTotpUri] = useState("")
  const [backupCodes, setBackupCodes] = useState<string[]>([])
  const {
    copied: setupKeyCopied,
    copy: copySetupKeyValue,
    reset: resetSetupKeyCopy
  } = useCopyToClipboard({
    onError: () => toast.danger(twoFactorLocalization.setupKeyCopyFailed)
  })

  const qrCode = useMemo(
    () => (totpUri ? createQrCodeSvgData(totpUri) : null),
    [totpUri]
  )
  // Manual entry fallback for authenticator apps that can't scan. The URI is
  // an `otpauth://` URL, so the secret is just a query parameter.
  const setupKey = useMemo(() => {
    if (!totpUri) return null

    try {
      return new URL(totpUri).searchParams.get("secret")
    } catch {
      return null
    }
  }, [totpUri])

  const copySetupKey = async () => {
    if (!setupKey) return

    await copySetupKeyValue(setupKey)
  }

  const {
    mutateAsync: enableTwoFactor,
    isPending: isEnabling,
    reset: resetEnrollment
  } = useEnableTwoFactor(twoFactorClient, {
    onSuccess: (data) => {
      if (data.method === "otp") {
        toast.success(twoFactorLocalization.twoFactorEnabled)
        handleOpenChange(false)
        return
      }

      setTotpUri(data.totpURI)
      setBackupCodes(data.backupCodes)
      setStep("verify")
    }
  })

  const { mutateAsync: verifyTotp, isPending: isVerifying } = useVerifyTotp(
    twoFactorClient,
    {
      onError: () => form.setFieldValue("code", ""),
      onSuccess: () => {
        toast.success(twoFactorLocalization.twoFactorEnabled)
        setStep("backupCodes")
      }
    }
  )

  const isPending = isEnabling || isVerifying || isResolvingPasswordRequirement

  const form = useAuthForm({
    defaultValues: { code: "", password: "" },
    onSubmit: async ({ value }) => {
      if (step === "backupCodes") {
        handleOpenChange(false)
        return
      }
      if (step === "verify") {
        await verifyCode(value.code)
        return
      }
      await enableTwoFactor(
        requiresPassword ? { method, password: value.password } : { method }
      )
    }
  })

  const verifyCode = async (completedCode: string) => {
    if (isPending || step !== "verify" || completedCode.length !== codeLength) {
      return
    }

    await verifyTotp({ code: completedCode })
  }

  const handleOpenChange = (open: boolean) => {
    onOpenChange(open)

    if (!open) {
      setStep("password")
      setMethod(enrollmentMethods[0] ?? "totp")
      setTotpUri("")
      setBackupCodes([])
      form.reset()
      resetSetupKeyCopy()
      // Clears the resolved TOTP URI and backup codes from the mutation cache.
      resetEnrollment()
    }
  }

  const submitLabel =
    step === "backupCodes"
      ? twoFactorLocalization.done
      : step === "verify"
        ? twoFactorLocalization.verify
        : twoFactorLocalization.enableTwoFactor

  return (
    <AlertDialog.Backdrop isOpen={isOpen} onOpenChange={handleOpenChange}>
      <AlertDialog.Container>
        <AlertDialog.Dialog>
          <form.AppForm>
            <form.AuthFormRoot>
              <AlertDialog.CloseTrigger />

              <AlertDialog.Header>
                <AlertDialog.Icon status="default">
                  <ShieldCheck />
                </AlertDialog.Icon>

                <AlertDialog.Heading>
                  {twoFactorLocalization.twoFactor}
                </AlertDialog.Heading>
              </AlertDialog.Header>

              <AlertDialog.Body className="overflow-visible">
                {step === "password" && (
                  <>
                    <p className="text-muted text-sm">
                      {requiresPassword
                        ? twoFactorLocalization.passwordConfirmation
                        : twoFactorLocalization.twoFactorDescription}
                    </p>

                    {enrollmentMethods.length > 1 && (
                      <Tabs
                        className="mt-4"
                        selectedKey={method}
                        onSelectionChange={(key) =>
                          setMethod(String(key) as TwoFactorMethod)
                        }
                        variant="secondary"
                      >
                        <Tabs.ListContainer>
                          <Tabs.List
                            aria-label={
                              twoFactorLocalization.chooseEnrollmentMethod
                            }
                          >
                            {enrollmentMethods.includes("totp") && (
                              <Tabs.Tab id="totp">
                                <Smartphone
                                  aria-hidden="true"
                                  className="text-muted"
                                />
                                {twoFactorLocalization.authenticatorApp}
                                <Tabs.Indicator />
                              </Tabs.Tab>
                            )}
                            {enrollmentMethods.includes("otp") && (
                              <Tabs.Tab id="otp">
                                <Envelope
                                  aria-hidden="true"
                                  className="text-muted"
                                />
                                {twoFactorLocalization.deliveredCode}
                                <Tabs.Indicator />
                              </Tabs.Tab>
                            )}
                          </Tabs.List>
                        </Tabs.ListContainer>
                      </Tabs>
                    )}

                    <p className="text-muted mt-4 text-sm">
                      {method === "totp"
                        ? twoFactorLocalization.authenticatorAppDescription
                        : twoFactorLocalization.deliveredCodeDescription}
                    </p>

                    {requiresPassword && (
                      <form.AppField
                        name="password"
                        validators={{
                          onChange: ({ value }) =>
                            validateStringLength(value, {
                              requiredMessage: localization.auth.fieldRequired
                            })
                        }}
                      >
                        {(field) => (
                          <TextField
                            className="mt-4"
                            isInvalid={isAuthFormFieldInvalid(field.state.meta)}
                            name={field.name}
                            autoComplete="current-password"
                            isDisabled={isPending}
                            validationBehavior="aria"
                            value={field.state.value}
                            onBlur={field.handleBlur}
                            onChange={field.handleChange}
                          >
                            <Label>{localization.auth.password}</Label>
                            <Input
                              autoFocus
                              type="password"
                              placeholder={
                                localization.auth.passwordPlaceholder
                              }
                              variant="secondary"
                            />
                            <field.AuthFormFieldError />
                          </TextField>
                        )}
                      </form.AppField>
                    )}
                  </>
                )}

                {step === "verify" && (
                  <div className="flex flex-col items-center gap-4">
                    <p className="text-muted text-sm">
                      {twoFactorLocalization.scanQrCode}
                    </p>

                    {qrCode && (
                      <svg
                        aria-hidden="true"
                        className="size-44 rounded-lg border border-border"
                        viewBox={`0 0 ${qrCode.size} ${qrCode.size}`}
                      >
                        <path
                          fill="white"
                          d={`M0 0h${qrCode.size}v${qrCode.size}H0z`}
                        />
                        <path
                          fill="black"
                          d={qrCode.path}
                          shapeRendering="crispEdges"
                        />
                      </svg>
                    )}

                    {setupKey && (
                      <TextField fullWidth value={setupKey}>
                        <Label className="text-muted text-xs">
                          {twoFactorLocalization.setupKey}
                        </Label>

                        <InputGroup fullWidth variant="secondary">
                          <InputGroup.Input
                            readOnly
                            className="font-mono text-xs"
                          />

                          <InputGroup.Suffix className="px-0">
                            <Button
                              isIconOnly
                              aria-label={
                                setupKeyCopied
                                  ? twoFactorLocalization.setupKeyCopied
                                  : localization.settings.copyToClipboard
                              }
                              size="sm"
                              type="button"
                              variant="ghost"
                              onPress={copySetupKey}
                            >
                              {setupKeyCopied ? <Check /> : <Copy />}
                            </Button>
                          </InputGroup.Suffix>
                        </InputGroup>
                      </TextField>
                    )}

                    <form.AppField name="code">
                      {(field) => (
                        <OtpField
                          autoFocus
                          className="w-full"
                          isDisabled={isPending}
                          label={twoFactorLocalization.authenticatorCode}
                          length={codeLength}
                          name={field.name}
                          value={field.state.value}
                          onChange={field.handleChange}
                          onComplete={() => void submitAuthForm(form)}
                        />
                      )}
                    </form.AppField>
                  </div>
                )}

                {step === "backupCodes" && <BackupCodes codes={backupCodes} />}
              </AlertDialog.Body>

              <AlertDialog.Footer>
                {step !== "backupCodes" && (
                  <Button
                    slot="close"
                    variant="tertiary"
                    isDisabled={isPending}
                  >
                    {localization.settings.cancel}
                  </Button>
                )}

                <form.Subscribe selector={(state) => state.values.code}>
                  {(code) => (
                    <form.AuthFormSubmitButton
                      isPending={isPending}
                      isDisabled={
                        isPending ||
                        (step === "verify" && code.length !== codeLength)
                      }
                    >
                      {submitLabel}
                    </form.AuthFormSubmitButton>
                  )}
                </form.Subscribe>
              </AlertDialog.Footer>
              <form.AuthFormServerError />
            </form.AuthFormRoot>
          </form.AppForm>
        </AlertDialog.Dialog>
      </AlertDialog.Container>
    </AlertDialog.Backdrop>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/two-factor/enable-two-factor-dialog.tsx
import { createQrCodeSvgData } from "@better-auth-ui/core"
import {
  enableTwoFactorOptions,
  type TwoFactorAuthClient,
  type TwoFactorMethod,
  verifyTotpOptions
} from "@better-auth-ui/core/plugins/two-factor"
import {
  createCopyToClipboard,
  useAuth,
  useAuthPlugin
} from "@better-auth-ui/solid"
import { createMutation } from "@tanstack/solid-query"
import { Check, Copy, Mail, ShieldCheck, Smartphone } from "lucide-solid"
import { createSignal, Show } from "solid-js"
import { toast } from "solid-sonner"
import { OtpField } from "@/components/auth/otp-field"
import { BackupCodes } from "@/components/auth/two-factor/backup-codes"
import { Button } from "@/components/ui/button"
import {
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog"
import { Field, FieldLabel } from "@/components/ui/field"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupButton,
  InputGroupInput
} from "@/components/ui/input-group"
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { twoFactorPlugin } from "@/lib/auth/two-factor-plugin"
import { useTwoFactorPasswordRequirement } from "@/lib/auth/use-two-factor-password"
import { createAuthForm, submitAuthForm } from "../auth-form"

type EnrollmentStep = "password" | "verify" | "backupCodes"

/**
 * Two-factor enrollment with authenticator-app and delivered-code methods.
 *
 * TOTP continues through QR verification and backup-code capture. OTP becomes
 * active as soon as Better Auth accepts the enrollment request.
 */
export function EnableTwoFactorDialog(props: {
  onOpenChange: (open: boolean) => void
}) {
  const auth = useAuth()
  const {
    codeLength,
    enrollmentMethods,
    localization: twoFactorLocalization
  } = useAuthPlugin(twoFactorPlugin)
  const { isPending: isResolvingPasswordRequirement, requiresPassword } =
    useTwoFactorPasswordRequirement()

  const [step, setStep] = createSignal<EnrollmentStep>("password")
  const [method, setMethod] = createSignal<TwoFactorMethod>(
    enrollmentMethods[0] ?? "totp"
  )
  const [totpUri, setTotpUri] = createSignal("")
  const [backupCodes, setBackupCodes] = createSignal<string[]>([])
  const { copied: setupKeyCopied, copy: copySetupKey } = createCopyToClipboard({
    onError: () => toast.error(twoFactorLocalization.setupKeyCopyFailed)
  })

  const qrCode = () => (totpUri() ? createQrCodeSvgData(totpUri()) : null)

  // Manual entry fallback for authenticator apps that can't scan. The URI is
  // an `otpauth://` URL, so the secret is just a query parameter.
  const setupKey = () => {
    if (!totpUri()) return null

    try {
      return new URL(totpUri()).searchParams.get("secret")
    } catch {
      return null
    }
  }

  const twoFactorClient = () => auth.authClient as TwoFactorAuthClient

  const enableTwoFactor = createMutation(() => ({
    ...enableTwoFactorOptions(twoFactorClient()),
    onSuccess: (data) => {
      if (data.method === "otp") {
        toast.success(twoFactorLocalization.twoFactorEnabled)
        props.onOpenChange(false)
        return
      }

      setTotpUri(data.totpURI)
      setBackupCodes(data.backupCodes)
      setStep("verify")
    }
  }))

  const verifyTotp = createMutation(() => ({
    ...verifyTotpOptions(twoFactorClient()),
    onError: () => form.setFieldValue("code", ""),
    onSuccess: () => {
      toast.success(twoFactorLocalization.twoFactorEnabled)
      setStep("backupCodes")
    }
  }))

  const isPending = () =>
    enableTwoFactor.isPending ||
    verifyTotp.isPending ||
    isResolvingPasswordRequirement()

  const verifyCode = async (completedCode: string) => {
    if (
      isPending() ||
      step() !== "verify" ||
      completedCode.length !== codeLength
    ) {
      return
    }

    form.setFieldValue("code", completedCode)
    await submitAuthForm(form, auth.localization.auth.callbackFailedTitle)
  }

  const form = createAuthForm(() => ({
    defaultValues: { code: "", password: "" },
    onSubmit: async ({ value }) => {
      if (step() === "backupCodes") {
        props.onOpenChange(false)
        return
      }
      if (step() === "verify") {
        await verifyTotp.mutateAsync({ code: value.code } as Parameters<
          typeof verifyTotp.mutateAsync
        >[0])
        return
      }
      await enableTwoFactor.mutateAsync(
        (requiresPassword()
          ? { method: method(), password: value.password }
          : { method: method() }) as Parameters<
          typeof enableTwoFactor.mutateAsync
        >[0]
      )
    }
  }))
  const code = form.useSelector((state) => state.values.code)

  const submitLabel = () => {
    if (step() === "backupCodes") return twoFactorLocalization.done
    if (step() === "verify") return twoFactorLocalization.verify

    return twoFactorLocalization.enableTwoFactor
  }

  const description = () => {
    if (step() === "verify") return twoFactorLocalization.scanQrCode
    if (step() === "password" && requiresPassword())
      return twoFactorLocalization.passwordConfirmation

    return twoFactorLocalization.twoFactorDescription
  }

  return (
    <DialogContent>
      <form.AppForm>
        <form.AuthFormRoot
          class="flex flex-col gap-6"
          serverErrorMessage={auth.localization.auth.callbackFailedTitle}
        >
          <DialogHeader>
            <div class="flex size-10 items-center justify-center rounded-md bg-muted">
              <ShieldCheck class="size-4.5" />
            </div>

            <DialogTitle>{twoFactorLocalization.twoFactor}</DialogTitle>
            <DialogDescription>{description()}</DialogDescription>
          </DialogHeader>

          <Show when={step() === "password"}>
            <div class="flex flex-col gap-4">
              <Show when={enrollmentMethods.length > 1}>
                <Tabs value={method()} onChange={setMethod}>
                  <TabsList
                    aria-label={twoFactorLocalization.chooseEnrollmentMethod}
                    class="w-full"
                  >
                    <Show when={enrollmentMethods.includes("totp")}>
                      <TabsTrigger value="totp">
                        <Smartphone
                          aria-hidden="true"
                          class="text-muted-foreground"
                        />
                        {twoFactorLocalization.authenticatorApp}
                      </TabsTrigger>
                    </Show>
                    <Show when={enrollmentMethods.includes("otp")}>
                      <TabsTrigger value="otp">
                        <Mail
                          aria-hidden="true"
                          class="text-muted-foreground"
                        />
                        {twoFactorLocalization.deliveredCode}
                      </TabsTrigger>
                    </Show>
                  </TabsList>
                </Tabs>
              </Show>

              <p class="text-muted-foreground text-sm">
                {method() === "totp"
                  ? twoFactorLocalization.authenticatorAppDescription
                  : twoFactorLocalization.deliveredCodeDescription}
              </p>

              <Show when={requiresPassword()}>
                <form.AppField
                  name="password"
                  validators={{
                    onChange: ({ value }) =>
                      value ? undefined : auth.localization.auth.fieldRequired
                  }}
                >
                  {(field) => (
                    <field.AuthFormTextField
                      autocomplete="current-password"
                      autofocus
                      disabled={isPending()}
                      id="enable-two-factor-password"
                      label={auth.localization.auth.password}
                      placeholder={auth.localization.auth.passwordPlaceholder}
                      type="password"
                    />
                  )}
                </form.AppField>
              </Show>
            </div>
          </Show>

          <Show when={step() === "verify"}>
            <div class="flex flex-col items-center gap-4">
              <Show when={qrCode()}>
                {(data) => (
                  <svg
                    aria-hidden="true"
                    class="size-44 rounded-md border"
                    viewBox={`0 0 ${data().size} ${data().size}`}
                  >
                    <path
                      d={`M0 0h${data().size}v${data().size}H0z`}
                      fill="white"
                    />
                    <path
                      d={data().path}
                      fill="black"
                      shape-rendering="crispEdges"
                    />
                  </svg>
                )}
              </Show>

              <Show when={setupKey()}>
                {(key) => (
                  <Field class="w-full gap-1">
                    <FieldLabel
                      class="text-muted-foreground text-xs"
                      for="two-factor-setup-key"
                    >
                      {twoFactorLocalization.setupKey}
                    </FieldLabel>

                    <InputGroup>
                      <InputGroupInput
                        class="font-mono text-xs"
                        id="two-factor-setup-key"
                        readonly
                        value={key()}
                      />

                      <InputGroupAddon align="inline-end">
                        <InputGroupButton
                          aria-label={
                            setupKeyCopied()
                              ? twoFactorLocalization.setupKeyCopied
                              : auth.localization.settings.copyToClipboard
                          }
                          onClick={() => copySetupKey(key())}
                          size="icon-xs"
                          type="button"
                        >
                          <Show fallback={<Copy />} when={setupKeyCopied()}>
                            <Check />
                          </Show>
                        </InputGroupButton>
                      </InputGroupAddon>
                    </InputGroup>
                  </Field>
                )}
              </Show>

              <OtpField
                autofocus
                class="w-full"
                disabled={isPending()}
                id="enable-two-factor-code"
                label={twoFactorLocalization.authenticatorCode}
                length={codeLength}
                name="code"
                onInput={(value) => form.setFieldValue("code", value)}
                onComplete={(value) => void verifyCode(value)}
                value={code()}
              />
            </div>
          </Show>

          <Show when={step() === "backupCodes"}>
            <BackupCodes codes={backupCodes()} />
          </Show>

          <DialogFooter>
            <Show when={step() !== "backupCodes"}>
              <DialogClose
                as={Button}
                disabled={isPending()}
                type="button"
                variant="outline"
              >
                {auth.localization.settings.cancel}
              </DialogClose>
            </Show>

            <form.AuthFormSubmitButton
              disabled={
                isPending() ||
                (step() === "verify" && code().length !== codeLength)
              }
            >
              {submitLabel()}
            </form.AuthFormSubmitButton>
          </DialogFooter>
          <form.AuthFormServerError />
        </form.AuthFormRoot>
      </form.AppForm>
    </DialogContent>
  )
}
