// examples/start-solid-zaidan-example/src/components/auth/sso/sso-provider-setup.tsx
import { validateAbsoluteUrl, validateStringLength } from "@better-auth-ui/core"
import type {
  RegisterSsoProviderData,
  RegisterSsoProviderParams,
  SsoAuthClient
} from "@better-auth-ui/core/plugins/sso"
import { useAuth, useAuthPlugin } from "@better-auth-ui/solid"
import { useRegisterSsoProvider } from "@better-auth-ui/solid/plugins/sso"
import type { BetterFetchError } from "better-auth/client"
import { FileCode2, KeyRound } from "lucide-solid"
import { createSignal, Show } from "solid-js"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle
} from "@/components/ui/card"
import {
  Field,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel
} from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Textarea } from "@/components/ui/textarea"
import { ssoPlugin } from "@/lib/auth/sso-plugin"
import { cn } from "@/lib/utils"
import { createAuthForm, isAuthFormFieldInvalid } from "../auth-form"

type SsoProtocol = "oidc" | "saml"

type SsoProviderFormValues = {
  clientId: string
  clientSecret: string
  domain: string
  entryPoint: string
  identityProviderMetadata: string
  issuer: string
  organizationId: string
  protocol: SsoProtocol
  providerId: string
}

export type SsoProviderSetupProps = {
  class?: string
  defaultOrganizationId?: string
  organizationId?: string
  onRegistered?: (provider: RegisterSsoProviderData) => void
}

const getErrorMessage = (error: Error | null | undefined) => {
  const authError = error as BetterFetchError | null | undefined
  return authError?.error?.message ?? authError?.message
}

export function SsoProviderSetup(props: SsoProviderSetupProps) {
  const auth = useAuth()
  const { localization } = useAuthPlugin(ssoPlugin)
  const [created, setCreated] = createSignal(false)
  const register = useRegisterSsoProvider(auth.authClient as SsoAuthClient)
  const form = createAuthForm(() => ({
    defaultValues: {
      clientId: "",
      clientSecret: "",
      domain: "",
      entryPoint: "",
      identityProviderMetadata: "",
      issuer: "",
      organizationId: props.defaultOrganizationId ?? "",
      protocol: "oidc" as SsoProtocol,
      providerId: ""
    } satisfies SsoProviderFormValues,
    onSubmit: async ({ value }) => {
      setCreated(false)
      const common = {
        providerId: value.providerId.trim(),
        issuer: value.issuer.trim(),
        domain: value.domain.trim(),
        organizationId:
          props.organizationId || value.organizationId.trim() || undefined
      }
      const params =
        value.protocol === "oidc"
          ? {
              ...common,
              oidcConfig: {
                clientId: value.clientId.trim(),
                clientSecret: value.clientSecret.trim()
              }
            }
          : {
              ...common,
              samlConfig: {
                entryPoint: value.entryPoint.trim(),
                idpMetadata: {
                  metadata: value.identityProviderMetadata.trim()
                }
              }
            }

      try {
        const provider = await register.mutateAsync(
          params as RegisterSsoProviderParams<SsoAuthClient>
        )
        setCreated(true)
        props.onRegistered?.(provider)
      } catch {
        // The mutation exposes its error below the fields.
      }
    }
  }))

  return (
    <form.AppForm>
      <form.AuthFormRoot class={cn("w-full max-w-xl", props.class)}>
        <Card>
          <CardHeader>
            <CardTitle>{localization.providerSetup}</CardTitle>
            <CardDescription>
              {localization.providerSetupDescription}
            </CardDescription>
          </CardHeader>
          <CardContent>
            <FieldGroup>
              <div class="grid gap-4 sm:grid-cols-2">
                <form.AppField
                  name="providerId"
                  validators={{
                    onChange: ({ value }) =>
                      validateStringLength(value, {
                        requiredMessage: auth.localization.auth.fieldRequired,
                        trim: true
                      })
                  }}
                >
                  {(field) => {
                    const isInvalid = () =>
                      isAuthFormFieldInvalid(field().state.meta)

                    return (
                      <Field data-invalid={isInvalid()}>
                        <FieldLabel for="solid-sso-provider-id">
                          {localization.providerId}
                        </FieldLabel>
                        <Input
                          id="solid-sso-provider-id"
                          name={field().name}
                          onBlur={field().handleBlur}
                          onInput={(event) =>
                            field().handleChange(event.currentTarget.value)
                          }
                          required
                          value={field().state.value}
                          aria-invalid={isInvalid()}
                        />
                        <field.AuthFormFieldError />
                      </Field>
                    )
                  }}
                </form.AppField>
                <form.AppField
                  name="domain"
                  validators={{
                    onChange: ({ value }) =>
                      validateStringLength(value, {
                        requiredMessage: auth.localization.auth.fieldRequired,
                        trim: true
                      })
                  }}
                >
                  {(field) => {
                    const isInvalid = () =>
                      isAuthFormFieldInvalid(field().state.meta)

                    return (
                      <Field data-invalid={isInvalid()}>
                        <FieldLabel for="solid-sso-domain">
                          {localization.domain}
                        </FieldLabel>
                        <Input
                          id="solid-sso-domain"
                          name={field().name}
                          onBlur={field().handleBlur}
                          onInput={(event) =>
                            field().handleChange(event.currentTarget.value)
                          }
                          placeholder="example.com"
                          required
                          value={field().state.value}
                          aria-invalid={isInvalid()}
                        />
                        <field.AuthFormFieldError />
                      </Field>
                    )
                  }}
                </form.AppField>
              </div>
              <form.AppField
                name="issuer"
                validators={{
                  onChange: ({ value }) =>
                    validateAbsoluteUrl(value, {
                      invalidMessage: localization.invalidUrl,
                      requiredMessage: auth.localization.auth.fieldRequired
                    })
                }}
              >
                {(field) => {
                  const isInvalid = () =>
                    isAuthFormFieldInvalid(field().state.meta)

                  return (
                    <Field data-invalid={isInvalid()}>
                      <FieldLabel for="solid-sso-issuer">
                        {localization.issuer}
                      </FieldLabel>
                      <Input
                        id="solid-sso-issuer"
                        name={field().name}
                        onBlur={field().handleBlur}
                        onInput={(event) =>
                          field().handleChange(event.currentTarget.value)
                        }
                        placeholder="https://idp.example.com"
                        required
                        type="url"
                        value={field().state.value}
                        aria-invalid={isInvalid()}
                      />
                      <field.AuthFormFieldError />
                    </Field>
                  )
                }}
              </form.AppField>
              <Show when={!props.organizationId}>
                <form.Field name="organizationId">
                  {(field) => (
                    <Field>
                      <FieldLabel for="solid-sso-organization-id">
                        {localization.organizationId}
                      </FieldLabel>
                      <Input
                        id="solid-sso-organization-id"
                        name={field().name}
                        onBlur={field().handleBlur}
                        onInput={(event) =>
                          field().handleChange(event.currentTarget.value)
                        }
                        value={field().state.value}
                      />
                    </Field>
                  )}
                </form.Field>
              </Show>
              <form.Field name="protocol">
                {(protocolField) => (
                  <Tabs
                    value={protocolField().state.value}
                    onChange={(value) =>
                      protocolField().handleChange(value as SsoProtocol)
                    }
                  >
                    <TabsList aria-label={localization.providerSetup}>
                      <TabsTrigger value="oidc">
                        <KeyRound
                          aria-hidden="true"
                          class="text-muted-foreground"
                        />
                        {localization.oidc}
                      </TabsTrigger>
                      <TabsTrigger value="saml">
                        <FileCode2
                          aria-hidden="true"
                          class="text-muted-foreground"
                        />
                        {localization.saml}
                      </TabsTrigger>
                    </TabsList>
                    <TabsContent class="grid gap-4 sm:grid-cols-2" value="oidc">
                      <form.AppField
                        name="clientId"
                        validators={{
                          onChange: ({ value }) =>
                            validateStringLength(value, {
                              requiredMessage:
                                auth.localization.auth.fieldRequired,
                              trim: true
                            })
                        }}
                      >
                        {(field) => {
                          const isInvalid = () =>
                            isAuthFormFieldInvalid(field().state.meta)

                          return (
                            <Field data-invalid={isInvalid()}>
                              <FieldLabel for="solid-sso-client-id">
                                {localization.clientId}
                              </FieldLabel>
                              <Input
                                autocomplete="off"
                                id="solid-sso-client-id"
                                name={field().name}
                                onBlur={field().handleBlur}
                                onInput={(event) =>
                                  field().handleChange(
                                    event.currentTarget.value
                                  )
                                }
                                required
                                value={field().state.value}
                                aria-invalid={isInvalid()}
                              />
                              <field.AuthFormFieldError />
                            </Field>
                          )
                        }}
                      </form.AppField>
                      <form.AppField
                        name="clientSecret"
                        validators={{
                          onChange: ({ value }) =>
                            validateStringLength(value, {
                              requiredMessage:
                                auth.localization.auth.fieldRequired,
                              trim: true
                            })
                        }}
                      >
                        {(field) => {
                          const isInvalid = () =>
                            isAuthFormFieldInvalid(field().state.meta)

                          return (
                            <Field data-invalid={isInvalid()}>
                              <FieldLabel for="solid-sso-client-secret">
                                {localization.clientSecret}
                              </FieldLabel>
                              <Input
                                autocomplete="new-password"
                                id="solid-sso-client-secret"
                                name={field().name}
                                onBlur={field().handleBlur}
                                onInput={(event) =>
                                  field().handleChange(
                                    event.currentTarget.value
                                  )
                                }
                                required
                                type="password"
                                value={field().state.value}
                                aria-invalid={isInvalid()}
                              />
                              <field.AuthFormFieldError />
                            </Field>
                          )
                        }}
                      </form.AppField>
                    </TabsContent>
                    <TabsContent class="flex flex-col gap-4" value="saml">
                      <form.AppField
                        name="entryPoint"
                        validators={{
                          onChange: ({ value }) =>
                            validateAbsoluteUrl(value, {
                              invalidMessage: localization.invalidUrl,
                              requiredMessage:
                                auth.localization.auth.fieldRequired
                            })
                        }}
                      >
                        {(field) => {
                          const isInvalid = () =>
                            isAuthFormFieldInvalid(field().state.meta)

                          return (
                            <Field data-invalid={isInvalid()}>
                              <FieldLabel for="solid-sso-entry-point">
                                {localization.entryPoint}
                              </FieldLabel>
                              <Input
                                id="solid-sso-entry-point"
                                name={field().name}
                                onBlur={field().handleBlur}
                                onInput={(event) =>
                                  field().handleChange(
                                    event.currentTarget.value
                                  )
                                }
                                required
                                type="url"
                                value={field().state.value}
                                aria-invalid={isInvalid()}
                              />
                              <field.AuthFormFieldError />
                            </Field>
                          )
                        }}
                      </form.AppField>
                      <form.AppField
                        name="identityProviderMetadata"
                        validators={{
                          onChange: ({ value }) =>
                            validateStringLength(value, {
                              requiredMessage:
                                auth.localization.auth.fieldRequired,
                              trim: true
                            })
                        }}
                      >
                        {(field) => {
                          const isInvalid = () =>
                            isAuthFormFieldInvalid(field().state.meta)

                          return (
                            <Field data-invalid={isInvalid()}>
                              <FieldLabel for="solid-sso-idp-metadata">
                                {localization.identityProviderMetadata}
                              </FieldLabel>
                              <Textarea
                                class="min-h-40 font-mono text-xs"
                                id="solid-sso-idp-metadata"
                                name={field().name}
                                onBlur={field().handleBlur}
                                onInput={(event) =>
                                  field().handleChange(
                                    event.currentTarget.value
                                  )
                                }
                                required
                                value={field().state.value}
                                aria-invalid={isInvalid()}
                              />
                              <field.AuthFormFieldError />
                            </Field>
                          )
                        }}
                      </form.AppField>
                    </TabsContent>
                  </Tabs>
                )}
              </form.Field>
              <FieldError>{getErrorMessage(register.error)}</FieldError>
              <Show when={created()}>
                <FieldDescription role="status">
                  {localization.providerCreated}
                </FieldDescription>
              </Show>
            </FieldGroup>
          </CardContent>
          <CardFooter class="justify-end">
            <form.AuthFormSubmitButton disabled={register.isPending}>
              {localization.addProvider}
            </form.AuthFormSubmitButton>
          </CardFooter>
        </Card>
      </form.AuthFormRoot>
    </form.AppForm>
  )
}

// packages/heroui/src/components/auth/sso/sso-provider-setup.tsx
"use client"

import { validateAbsoluteUrl, validateStringLength } from "@better-auth-ui/core"
import type {
  RegisterSsoProviderData,
  RegisterSsoProviderParams,
  SsoAuthClient
} from "@better-auth-ui/core/plugins/sso"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import { useRegisterSsoProvider } from "@better-auth-ui/react/plugins/sso"
import { FileCode, Key } from "@gravity-ui/icons"
import {
  Alert,
  Card,
  type CardProps,
  cn,
  FieldError,
  Input,
  Label,
  Tabs,
  TextArea,
  TextField
} from "@heroui/react"
import type { BetterFetchError } from "better-auth/client"
import { useState } from "react"
import { ssoPlugin } from "../../../lib/auth/sso-plugin"
import { isAuthFormFieldInvalid, useAuthForm } from "../auth-form"

type SsoProtocol = "oidc" | "saml"

type SsoProviderFormValues = {
  clientId: string
  clientSecret: string
  domain: string
  entryPoint: string
  identityProviderMetadata: string
  issuer: string
  organizationId: string
  protocol: SsoProtocol
  providerId: string
}

export type SsoProviderSetupProps = {
  defaultOrganizationId?: string
  organizationId?: string
  onRegistered?: (provider: RegisterSsoProviderData) => void
} & Omit<CardProps, "children">

const getErrorMessage = (error: Error | null) => {
  const authError = error as BetterFetchError | null
  return authError?.error?.message ?? authError?.message
}

/** Self-service form for registering an OIDC or SAML SSO provider. */
export function SsoProviderSetup({
  className,
  defaultOrganizationId,
  organizationId: fixedOrganizationId,
  onRegistered,
  variant,
  ...props
}: SsoProviderSetupProps) {
  const { authClient, localization: authLocalization } = useAuth()
  const { localization } = useAuthPlugin(ssoPlugin)
  const [created, setCreated] = useState(false)
  const register = useRegisterSsoProvider(authClient as SsoAuthClient)
  const form = useAuthForm({
    defaultValues: {
      clientId: "",
      clientSecret: "",
      domain: "",
      entryPoint: "",
      identityProviderMetadata: "",
      issuer: "",
      organizationId: defaultOrganizationId ?? "",
      protocol: "oidc" as SsoProtocol,
      providerId: ""
    } satisfies SsoProviderFormValues,
    onSubmit: async ({ value }) => {
      setCreated(false)
      const common = {
        providerId: value.providerId.trim(),
        issuer: value.issuer.trim(),
        domain: value.domain.trim(),
        organizationId:
          fixedOrganizationId || value.organizationId.trim() || undefined
      }
      const params =
        value.protocol === "oidc"
          ? {
              ...common,
              oidcConfig: {
                clientId: value.clientId.trim(),
                clientSecret: value.clientSecret.trim()
              }
            }
          : {
              ...common,
              samlConfig: {
                entryPoint: value.entryPoint.trim(),
                idpMetadata: {
                  metadata: value.identityProviderMetadata.trim()
                }
              }
            }

      try {
        const provider = await register.mutateAsync(
          params as RegisterSsoProviderParams<SsoAuthClient>
        )
        setCreated(true)
        onRegistered?.(provider)
      } catch {
        // The mutation exposes its error below the fields.
      }
    }
  })

  return (
    <Card className={cn(className)} variant={variant} {...props}>
      <Card.Header>
        <Card.Title>{localization.providerSetup}</Card.Title>
        <Card.Description>
          {localization.providerSetupDescription}
        </Card.Description>
      </Card.Header>
      <Card.Content>
        <form.AppForm>
          <form.AuthFormRoot className="flex flex-col gap-4">
            <div className="grid gap-4 sm:grid-cols-2">
              <form.AppField
                name="providerId"
                validators={{
                  onChange: ({ value }) =>
                    validateStringLength(value, {
                      requiredMessage: authLocalization.auth.fieldRequired,
                      trim: true
                    })
                }}
              >
                {(field) => (
                  <TextField
                    isInvalid={
                      isAuthFormFieldInvalid(field.state.meta) || undefined
                    }
                    isRequired
                    name={field.name}
                    onBlur={field.handleBlur}
                    onChange={field.handleChange}
                    value={field.state.value}
                    validationBehavior="aria"
                  >
                    <Label>{localization.providerId}</Label>
                    <Input variant="secondary" />
                    <field.AuthFormFieldError />
                  </TextField>
                )}
              </form.AppField>
              <form.AppField
                name="domain"
                validators={{
                  onChange: ({ value }) =>
                    validateStringLength(value, {
                      requiredMessage: authLocalization.auth.fieldRequired,
                      trim: true
                    })
                }}
              >
                {(field) => (
                  <TextField
                    isInvalid={
                      isAuthFormFieldInvalid(field.state.meta) || undefined
                    }
                    isRequired
                    name={field.name}
                    onBlur={field.handleBlur}
                    onChange={field.handleChange}
                    value={field.state.value}
                    validationBehavior="aria"
                  >
                    <Label>{localization.domain}</Label>
                    <Input placeholder="example.com" variant="secondary" />
                    <field.AuthFormFieldError />
                  </TextField>
                )}
              </form.AppField>
            </div>

            <form.AppField
              name="issuer"
              validators={{
                onChange: ({ value }) =>
                  validateAbsoluteUrl(value, {
                    invalidMessage: localization.invalidUrl,
                    requiredMessage: authLocalization.auth.fieldRequired
                  })
              }}
            >
              {(field) => (
                <TextField
                  isInvalid={
                    isAuthFormFieldInvalid(field.state.meta) || undefined
                  }
                  isRequired
                  name={field.name}
                  onBlur={field.handleBlur}
                  onChange={field.handleChange}
                  value={field.state.value}
                  validationBehavior="aria"
                >
                  <Label>{localization.issuer}</Label>
                  <Input
                    placeholder="https://idp.example.com"
                    type="url"
                    variant="secondary"
                  />
                  <field.AuthFormFieldError />
                </TextField>
              )}
            </form.AppField>

            {!fixedOrganizationId ? (
              <form.Field name="organizationId">
                {(field) => (
                  <TextField
                    name={field.name}
                    onBlur={field.handleBlur}
                    onChange={field.handleChange}
                    value={field.state.value}
                  >
                    <Label>{localization.organizationId}</Label>
                    <Input variant="secondary" />
                    <FieldError />
                  </TextField>
                )}
              </form.Field>
            ) : null}

            <form.Field name="protocol">
              {(protocolField) => (
                <Tabs
                  selectedKey={protocolField.state.value}
                  onSelectionChange={(key) =>
                    protocolField.handleChange(String(key) as SsoProtocol)
                  }
                  variant="secondary"
                >
                  <Tabs.ListContainer>
                    <Tabs.List aria-label={localization.providerSetup}>
                      <Tabs.Tab id="oidc">
                        <Key aria-hidden="true" className="text-muted" />
                        {localization.oidc}
                        <Tabs.Indicator />
                      </Tabs.Tab>
                      <Tabs.Tab id="saml">
                        <FileCode aria-hidden="true" className="text-muted" />
                        {localization.saml}
                        <Tabs.Indicator />
                      </Tabs.Tab>
                    </Tabs.List>
                  </Tabs.ListContainer>
                  <Tabs.Panel className="pt-4" id="oidc">
                    <div className="grid gap-4 sm:grid-cols-2">
                      <form.AppField
                        name="clientId"
                        validators={{
                          onChange: ({ value }) =>
                            validateStringLength(value, {
                              requiredMessage:
                                authLocalization.auth.fieldRequired,
                              trim: true
                            })
                        }}
                      >
                        {(field) => (
                          <TextField
                            isInvalid={
                              isAuthFormFieldInvalid(field.state.meta) ||
                              undefined
                            }
                            isRequired
                            name={field.name}
                            onBlur={field.handleBlur}
                            onChange={field.handleChange}
                            value={field.state.value}
                            validationBehavior="aria"
                          >
                            <Label>{localization.clientId}</Label>
                            <Input autoComplete="off" variant="secondary" />
                            <field.AuthFormFieldError />
                          </TextField>
                        )}
                      </form.AppField>
                      <form.AppField
                        name="clientSecret"
                        validators={{
                          onChange: ({ value }) =>
                            validateStringLength(value, {
                              requiredMessage:
                                authLocalization.auth.fieldRequired,
                              trim: true
                            })
                        }}
                      >
                        {(field) => (
                          <TextField
                            isInvalid={
                              isAuthFormFieldInvalid(field.state.meta) ||
                              undefined
                            }
                            isRequired
                            name={field.name}
                            onBlur={field.handleBlur}
                            onChange={field.handleChange}
                            value={field.state.value}
                            validationBehavior="aria"
                          >
                            <Label>{localization.clientSecret}</Label>
                            <Input
                              autoComplete="new-password"
                              type="password"
                              variant="secondary"
                            />
                            <field.AuthFormFieldError />
                          </TextField>
                        )}
                      </form.AppField>
                    </div>
                  </Tabs.Panel>
                  <Tabs.Panel className="flex flex-col gap-4 pt-4" id="saml">
                    <form.AppField
                      name="entryPoint"
                      validators={{
                        onChange: ({ value }) =>
                          validateAbsoluteUrl(value, {
                            invalidMessage: localization.invalidUrl,
                            requiredMessage: authLocalization.auth.fieldRequired
                          })
                      }}
                    >
                      {(field) => (
                        <TextField
                          isInvalid={
                            isAuthFormFieldInvalid(field.state.meta) ||
                            undefined
                          }
                          isRequired
                          name={field.name}
                          onBlur={field.handleBlur}
                          onChange={field.handleChange}
                          value={field.state.value}
                          validationBehavior="aria"
                        >
                          <Label>{localization.entryPoint}</Label>
                          <Input type="url" variant="secondary" />
                          <field.AuthFormFieldError />
                        </TextField>
                      )}
                    </form.AppField>
                    <form.AppField
                      name="identityProviderMetadata"
                      validators={{
                        onChange: ({ value }) =>
                          validateStringLength(value, {
                            requiredMessage:
                              authLocalization.auth.fieldRequired,
                            trim: true
                          })
                      }}
                    >
                      {(field) => (
                        <TextField
                          isInvalid={
                            isAuthFormFieldInvalid(field.state.meta) ||
                            undefined
                          }
                          isRequired
                          name={field.name}
                          onBlur={field.handleBlur}
                          onChange={field.handleChange}
                          value={field.state.value}
                          validationBehavior="aria"
                        >
                          <Label>{localization.identityProviderMetadata}</Label>
                          <TextArea
                            className="font-mono text-xs"
                            rows={8}
                            variant="secondary"
                          />
                          <field.AuthFormFieldError />
                        </TextField>
                      )}
                    </form.AppField>
                  </Tabs.Panel>
                </Tabs>
              )}
            </form.Field>

            {register.error ? (
              <Alert status="danger">
                <Alert.Indicator />
                <Alert.Content>
                  <Alert.Description>
                    {getErrorMessage(register.error)}
                  </Alert.Description>
                </Alert.Content>
              </Alert>
            ) : null}
            {created ? (
              <Alert status="success">
                <Alert.Indicator />
                <Alert.Content>
                  <Alert.Description>
                    {localization.providerCreated}
                  </Alert.Description>
                </Alert.Content>
              </Alert>
            ) : null}

            <form.AuthFormSubmitButton
              className="self-end"
              isDisabled={register.isPending}
            >
              {localization.addProvider}
            </form.AuthFormSubmitButton>
          </form.AuthFormRoot>
        </form.AppForm>
      </Card.Content>
    </Card>
  )
}
